load data infile 'Bicycles.csv'
into table bicycles_load
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
lines terminated by '\n'
IGNORE 1 ROWS;
(handle,
title,
body,
vendor,
type_,
tags,
published,
option1_Name,
Option1_Value,
Option2_Name,
Option2_Value,
Option3_Name,
Option3_Value,
Variant_SKU,
Variant_Grams,
Variant_Inventory_Tracker,
Variant_Inventory_Qty,
Variant_Inventory_Policy,
Variant_Fulfillment_Service,
Variant_Price,
Variant_Compare_At_Price,
Variant_Requires_Shipping,
Variant_Taxable,
Variant_Barcode,
Image_Src,
Image_Alt_Text,
Gift_Card,
SEO_Title,
SEO_Description,
Google_Product_Category,
Gender,
Age_Group,
MPN,
AdWords_Grouping,
AdWords_Labels,
Condition_,
Custom_Product,
Custom_Label0,
Custom_Label1,
Custom_Label2,
Custom_Label3,
Custom_Label4,
Variant_Image,
Variant_Weight_Unit);